# LOGISTIC REGRESSION

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns

In [7]:
df = pd.read_csv("C:/Users/OWUSU/Desktop/ML n DL/Data Files/2. ST Academy - Classification models resource files/House_price.csv",header=0)

In [8]:
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  poor_prop airport  n_hos_beds  n_hot_rooms waterbody  rainfall  \
0      24.7       4.98     YES       5.480      11.1920     River        23   
1      22.2       9.14      NO       7.332      12.1728      Lake        42   
2      22.2       4.03      NO       7.394     101.1200      None        38   
3      21.3       2.94     YES       9.268      11.2672      Lake        45   
4      21.3       5.33      NO       8.824      11.2896      Lake        55   

  bus_ter     parks  Sold  
0     YES  0.049347     0  
1     YES  0.046146     1  
2     YES  0.045764     0  
3     YES  0.047151     0  
4     YES  0.039474     0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   price        506 non-null    float64
 1   resid_area   506 non-null    float64
 2   air_qual     506 non-null    float64
 3   room_num     506 non-null    float64
 4   age          506 non-null    float64
 5   dist1        506 non-null    float64
 6   dist2        506 non-null    float64
 7   dist3        506 non-null    float64
 8   dist4        506 non-null    float64
 9   teachers     506 non-null    float64
 10  poor_prop    506 non-null    float64
 11  airport      506 non-null    object 
 12  n_hos_beds   498 non-null    float64
 13  n_hot_rooms  506 non-null    float64
 14  waterbody    506 non-null    object 
 15  rainfall     506 non-null    int64  
 16  bus_ter      506 non-null    object 
 17  parks        506 non-null    float64
 18  Sold         506 non-null    int64  
dtypes: float

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
x = df[["price"]]

In [13]:
y = df["Sold"]

In [14]:
clf_lrs = LogisticRegression()

In [15]:
clf_lrs.fit(x,y)

LogisticRegression()

In [16]:
print(clf_lrs.intercept_,clf_lrs.coef_)

[0.61477516] [[-0.03571865]]


In [17]:
# using_statsmodel

In [19]:
import statsmodels.api as sn

In [20]:
x_cons = sn.add_constant(x)

In [21]:
import statsmodels.discrete.discrete_model as sm

In [22]:
logit = sm.Logit(y,x_cons).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [23]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Fri, 07 Oct 2022   Pseudo R-squ.:                 0.01788
Time:                        08:49:31   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

In [24]:
#multiple variables


In [34]:
df = pd.get_dummies(df)

In [35]:
df.head()

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0   24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1   21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2   34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3   33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4   36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   

   teachers  ...  rainfall     parks  Sold  airport_NO  airport_YES  \
0      24.7  ...        23  0.049347     0           0            1   
1      22.2  ...        42  0.046146     1           1            0   
2      22.2  ...        38  0.045764     0           1            0   
3      21.3  ...        45  0.047151     0           0            1   
4      21.3  ...        55  0.039474     0           1            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_None  waterbody_River  \
0               0                         0               0                1   
1               1                         0               0                0   
2               0                         0               1                0   
3               1                         0               0                0   
4               1                         0               0                0   

   bus_ter_YES  
0            1  
1            1  
2            1  
3            1  
4            1  

[5 rows x 23 columns]

In [36]:
del df['airport_NO']

In [37]:
del df['waterbody_None']

In [40]:
df["avg_dist"] = (df.dist1+df.dist2+df.dist3+df.dist4)/4

In [41]:
del df['dist1']

In [42]:
del df['dist2']

In [43]:
del df['dist3']

In [44]:
del df['dist4']

In [45]:
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  airport_YES  \
0       5.480      11.1920        23  0.049347     0            1   
1       7.332      12.1728        42  0.046146     1            0   
2       7.394     101.1200        38  0.045764     0            0   
3       9.268      11.2672        45  0.047151     0            1   
4       8.824      11.2896        55  0.039474     0            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  bus_ter_YES  \
0               0                         0                1            1   
1               1                         0                0            1   
2               0                         0                0            1   
3               1                         0                0            1   
4               1                         0                0            1   

   avg_dist  
0    4.0875  
1    4.9675  
2    4.9675  
3    6.0650  
4    6.0625

In [52]:
df.corr()

price  resid_area  air_qual  room_num       age  \
price                     1.000000   -0.484754 -0.429300  0.696304 -0.377999   
resid_area               -0.484754    1.000000  0.763651 -0.391676  0.644779   
air_qual                 -0.429300    0.763651  1.000000 -0.302188  0.731470   
room_num                  0.696304   -0.391676 -0.302188  1.000000 -0.240265   
age                      -0.377999    0.644779  0.731470 -0.240265  1.000000   
teachers                  0.505655   -0.383248 -0.188933  0.355501 -0.261515   
poor_prop                -0.740836    0.603800  0.590879 -0.613808  0.602339   
n_hos_beds                0.109646    0.005827 -0.049954  0.032207 -0.021102   
n_hot_rooms               0.023122   -0.000839 -0.004882  0.030674  0.009380   
rainfall                 -0.047426    0.055810  0.092104 -0.064694  0.075198   
parks                    -0.391574    0.707635  0.915544 -0.282817  0.673850   
Sold                     -0.154698    0.024404 -0.004017  0.027148 -0.016291   
airport_YES               0.182867   -0.115401 -0.073903  0.163774  0.005101   
waterbody_Lake            0.036233   -0.026590 -0.046393 -0.004195  0.003452   
waterbody_Lake and River -0.037497    0.051649  0.013849  0.010554 -0.004354   
waterbody_River           0.071751   -0.098976 -0.037772  0.046251 -0.088609   
bus_ter_YES                    NaN         NaN       NaN       NaN       NaN   
avg_dist                  0.249289   -0.708022 -0.769247  0.205241 -0.747906   

                          teachers  poor_prop  n_hos_beds  n_hot_rooms  \
price                     0.505655  -0.740836    0.109646     0.023122   
resid_area               -0.383248   0.603800    0.005827    -0.000839   
air_qual                 -0.188933   0.590879   -0.049954    -0.004882   
room_num                  0.355501  -0.613808    0.032207     0.030674   
age                      -0.261515   0.602339   -0.021102     0.009380   
teachers                  1.000000  -0.374044   -0.008130    -0.023343   
poor_prop                -0.374044   1.000000   -0.066434     0.003337   
n_hos_beds               -0.008130  -0.066434    1.000000    -0.005461   
n_hot_rooms              -0.023343   0.003337   -0.005461     1.000000   
rainfall                 -0.045836   0.061581    0.058997    -0.004840   
parks                    -0.187004   0.552310   -0.072002     0.006262   
Sold                      0.042525  -0.082776    0.067391    -0.077333   
airport_YES               0.069437  -0.095054   -0.006412    -0.066012   
waterbody_Lake            0.048717   0.003197    0.042869     0.036442   
waterbody_Lake and River -0.046981   0.020620    0.059560    -0.006133   
waterbody_River           0.094256  -0.109004   -0.074934    -0.058431   
bus_ter_YES                    NaN        NaN         NaN          NaN   
avg_dist                  0.232452  -0.496967   -0.028028    -0.010177   

                          rainfall     parks      Sold  airport_YES  \
price                    -0.047426 -0.391574 -0.154698     0.182867   
resid_area                0.055810  0.707635  0.024404    -0.115401   
air_qual                  0.092104  0.915544 -0.004017    -0.073903   
room_num                 -0.064694 -0.282817  0.027148     0.163774   
age                       0.075198  0.673850 -0.016291     0.005101   
teachers                 -0.045836 -0.187004  0.042525     0.069437   
poor_prop                 0.061581  0.552310 -0.082776    -0.095054   
n_hos_beds                0.058997 -0.072002  0.067391    -0.006412   
n_hot_rooms              -0.004840  0.006262 -0.077333    -0.066012   
rainfall                  1.000000  0.078641 -0.040581    -0.013581   
parks                     0.078641  1.000000  0.004808    -0.052503   
Sold                     -0.040581  0.004808  1.000000    -0.070371   
airport_YES              -0.013581 -0.052503 -0.070371     1.000000   
waterbody_Lake           -0.015918 -0.034991 -0.061414     0.035491   
waterbody_Lake and River  0.109281  

In [53]:
del df['bus_ter_YES']

In [54]:
df.corr()

price  resid_area  air_qual  room_num       age  \
price                     1.000000   -0.484754 -0.429300  0.696304 -0.377999   
resid_area               -0.484754    1.000000  0.763651 -0.391676  0.644779   
air_qual                 -0.429300    0.763651  1.000000 -0.302188  0.731470   
room_num                  0.696304   -0.391676 -0.302188  1.000000 -0.240265   
age                      -0.377999    0.644779  0.731470 -0.240265  1.000000   
teachers                  0.505655   -0.383248 -0.188933  0.355501 -0.261515   
poor_prop                -0.740836    0.603800  0.590879 -0.613808  0.602339   
n_hos_beds                0.109646    0.005827 -0.049954  0.032207 -0.021102   
n_hot_rooms               0.023122   -0.000839 -0.004882  0.030674  0.009380   
rainfall                 -0.047426    0.055810  0.092104 -0.064694  0.075198   
parks                    -0.391574    0.707635  0.915544 -0.282817  0.673850   
Sold                     -0.154698    0.024404 -0.004017  0.027148 -0.016291   
airport_YES               0.182867   -0.115401 -0.073903  0.163774  0.005101   
waterbody_Lake            0.036233   -0.026590 -0.046393 -0.004195  0.003452   
waterbody_Lake and River -0.037497    0.051649  0.013849  0.010554 -0.004354   
waterbody_River           0.071751   -0.098976 -0.037772  0.046251 -0.088609   
avg_dist                  0.249289   -0.708022 -0.769247  0.205241 -0.747906   

                          teachers  poor_prop  n_hos_beds  n_hot_rooms  \
price                     0.505655  -0.740836    0.109646     0.023122   
resid_area               -0.383248   0.603800    0.005827    -0.000839   
air_qual                 -0.188933   0.590879   -0.049954    -0.004882   
room_num                  0.355501  -0.613808    0.032207     0.030674   
age                      -0.261515   0.602339   -0.021102     0.009380   
teachers                  1.000000  -0.374044   -0.008130    -0.023343   
poor_prop                -0.374044   1.000000   -0.066434     0.003337   
n_hos_beds               -0.008130  -0.066434    1.000000    -0.005461   
n_hot_rooms              -0.023343   0.003337   -0.005461     1.000000   
rainfall                 -0.045836   0.061581    0.058997    -0.004840   
parks                    -0.187004   0.552310   -0.072002     0.006262   
Sold                      0.042525  -0.082776    0.067391    -0.077333   
airport_YES               0.069437  -0.095054   -0.006412    -0.066012   
waterbody_Lake            0.048717   0.003197    0.042869     0.036442   
waterbody_Lake and River -0.046981   0.020620    0.059560    -0.006133   
waterbody_River           0.094256  -0.109004   -0.074934    -0.058431   
avg_dist                  0.232452  -0.496967   -0.028028    -0.010177   

                          rainfall     parks      Sold  airport_YES  \
price                    -0.047426 -0.391574 -0.154698     0.182867   
resid_area                0.055810  0.707635  0.024404    -0.115401   
air_qual                  0.092104  0.915544 -0.004017    -0.073903   
room_num                 -0.064694 -0.282817  0.027148     0.163774   
age                       0.075198  0.673850 -0.016291     0.005101   
teachers                 -0.045836 -0.187004  0.042525     0.069437   
poor_prop                 0.061581  0.552310 -0.082776    -0.095054   
n_hos_beds                0.058997 -0.072002  0.067391    -0.006412   
n_hot_rooms              -0.004840  0.006262 -0.077333    -0.066012   
rainfall                  1.000000  0.078641 -0.040581    -0.013581   
parks                     0.078641  1.000000  0.004808    -0.052503   
Sold                     -0.040581  0.004808  1.000000    -0.070371   
airport_YES              -0.013581 -0.052503 -0.070371     1.000000   
waterbody_Lake           -0.015918 -0.034991 -0.061414     0.035491   
waterbody_Lake and River  0.109281  0.013265 -0.003117    -0.070341   
waterbody_River          -0.036611 -0.048862  0.072842     0.017341   
avg_dist                 -0.037270 -0.707924 -0.

In [62]:
df = df.fillna(0)

In [63]:
df.head()

price  resid_area  room_num   age  teachers  poor_prop  n_hos_beds  \
0   24.0       32.31     6.575  65.2      24.7       4.98       5.480   
1   21.6       37.07     6.421  78.9      22.2       9.14       7.332   
2   34.7       37.07     7.185  61.1      22.2       4.03       7.394   
3   33.4       32.18     6.998  45.8      21.3       2.94       9.268   
4   36.2       32.18     7.147  54.2      21.3       5.33       8.824   

   n_hot_rooms  rainfall     parks  Sold  airport_YES  waterbody_Lake  \
0      11.1920        23  0.049347     0            1               0   
1      12.1728        42  0.046146     1            0               1   
2     101.1200        38  0.045764     0            0               0   
3      11.2672        45  0.047151     0            1               1   
4      11.2896        55  0.039474     0            0               1   

   waterbody_Lake and River  waterbody_River  avg_dist  
0                         0                1    4.0875  
1                         0                0    4.9675  
2                         0                0    4.9675  
3                         0                0    6.0650  
4                         0                0    6.0625

In [64]:
del df['air_qual']

KeyError: 'air_qual'

In [65]:
df.corr()

price  resid_area  room_num       age  teachers  \
price                     1.000000   -0.484754  0.696304 -0.377999  0.505655   
resid_area               -0.484754    1.000000 -0.391676  0.644779 -0.383248   
room_num                  0.696304   -0.391676  1.000000 -0.240265  0.355501   
age                      -0.377999    0.644779 -0.240265  1.000000 -0.261515   
teachers                  0.505655   -0.383248  0.355501 -0.261515  1.000000   
poor_prop                -0.740836    0.603800 -0.613808  0.602339 -0.374044   
n_hos_beds                0.114267   -0.001782  0.043987 -0.034799 -0.013410   
n_hot_rooms               0.023122   -0.000839  0.030674  0.009380 -0.023343   
rainfall                 -0.047426    0.055810 -0.064694  0.075198 -0.045836   
parks                    -0.391574    0.707635 -0.282817  0.673850 -0.187004   
Sold                     -0.154698    0.024404  0.027148 -0.016291  0.042525   
airport_YES               0.182867   -0.115401  0.163774  0.005101  0.069437   
waterbody_Lake            0.036233   -0.026590 -0.004195  0.003452  0.048717   
waterbody_Lake and River -0.037497    0.051649  0.010554 -0.004354 -0.046981   
waterbody_River           0.071751   -0.098976  0.046251 -0.088609  0.094256   
avg_dist                  0.249289   -0.708022  0.205241 -0.747906  0.232452   

                          poor_prop  n_hos_beds  n_hot_rooms  rainfall  \
price                     -0.740836    0.114267     0.023122 -0.047426   
resid_area                 0.603800   -0.001782    -0.000839  0.055810   
room_num                  -0.613808    0.043987     0.030674 -0.064694   
age                        0.602339   -0.034799     0.009380  0.075198   
teachers                  -0.374044   -0.013410    -0.023343 -0.045836   
poor_prop                  1.000000   -0.088075     0.003337  0.061581   
n_hos_beds                -0.088075    1.000000     0.000698  0.092130   
n_hot_rooms                0.003337    0.000698     1.000000 -0.004840   
rainfall                   0.061581    0.092130    -0.004840  1.000000   
parks                      0.552310   -0.097390     0.006262  0.078641   
Sold                      -0.082776    0.048987    -0.077333 -0.040581   
airport_YES               -0.095054   -0.033550    -0.066012 -0.013581   
waterbody_Lake             0.003197    0.002105     0.036442 -0.015918   
waterbody_Lake and River   0.020620    0.077939    -0.006133  0.109281   
waterbody_River           -0.109004   -0.100303    -0.058431 -0.036611   
avg_dist                  -0.496967    0.003405    -0.010177 -0.037270   

                             parks      Sold  airport_YES  waterbody_Lake  \
price                    -0.391574 -0.154698     0.182867        0.036233   
resid_area                0.707635  0.024404    -0.115401       -0.026590   
room_num                 -0.282817  0.027148     0.163774       -0.004195   
age                       0.673850 -0.016291     0.005101        0.003452   
teachers                 -0.187004  0.042525     0.069437        0.048717   
poor_prop                 0.552310 -0.082776    -0.095054        0.003197   
n_hos_beds               -0.097390  0.048987    -0.033550        0.002105   
n_hot_rooms               0.006262 -0.077333    -0.066012        0.036442   
rainfall                  0.078641 -0.040581    -0.013581       -0.015918   
parks                     1.000000  0.004808    -0.052503       -0.034991   
Sold                      0.004808  1.000000    -0.070371       -0.061414   
airport_YES              -0.052503 -0.070371     1.000000        0.035491   
waterbody_Lake           -0.034991 -0.061414     0.035491        1.000000   
waterbody_Lake and River  0.013265 -0.003117    -0.070341       -0.196747   
waterbody_River          -0.048862  0.072842     0.017341       -0.366563   
avg_dist                 -0.707924 -0.038810     0.021402        0.034890   

                          waterbody_Lake and River  waterbody_River  avg_dist  
price              

In [66]:
x_multi = df.drop("Sold",axis=1)

In [67]:
x_multi.head()

price  resid_area  room_num   age  teachers  poor_prop  n_hos_beds  \
0   24.0       32.31     6.575  65.2      24.7       4.98       5.480   
1   21.6       37.07     6.421  78.9      22.2       9.14       7.332   
2   34.7       37.07     7.185  61.1      22.2       4.03       7.394   
3   33.4       32.18     6.998  45.8      21.3       2.94       9.268   
4   36.2       32.18     7.147  54.2      21.3       5.33       8.824   

   n_hot_rooms  rainfall     parks  airport_YES  waterbody_Lake  \
0      11.1920        23  0.049347            1               0   
1      12.1728        42  0.046146            0               1   
2     101.1200        38  0.045764            0               0   
3      11.2672        45  0.047151            1               1   
4      11.2896        55  0.039474            0               1   

   waterbody_Lake and River  waterbody_River  avg_dist  
0                         0                1    4.0875  
1                         0                0    4.9675  
2                         0                0    4.9675  
3                         0                0    6.0650  
4                         0                0    6.0625

In [68]:
y_multi = df["Sold"]

In [69]:
y_multi.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [70]:
clf_lrs_multi = LogisticRegression()

In [71]:
clf_lrs_multi.fit(x_multi,y_multi)

C:\Users\OWUSU\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [72]:
print(clf_lrs_multi.intercept_,clf_lrs_multi.coef_)

[0.01156095] [[-0.24674934 -0.01597331  0.86188044 -0.00603863  0.24339939 -0.21070885
   0.11424007 -0.08205746 -0.00717488 -0.00906376 -0.1067786  -0.03566161
  -0.01091124  0.20066108 -0.32592209]]


In [73]:
#using statsmodels

In [75]:
x_multi_cons =sn.add_constant(x_multi)

In [76]:
logit_multi = sm.Logit(y_multi,x_multi_cons).fit()

Optimization terminated successfully.
         Current function value: 0.566192
         Iterations 7


In [77]:
logit_multi.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      490
Method:                           MLE   Df Model:                           15
Date:                Fri, 07 Oct 2022   Pseudo R-squ.:                  0.1783
Time:                        10:12:02   Log-Likelihood:                -286.49
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 2.771e-19
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -1.5073      2.611     -0.577      0.564      -6.625       3.610
price                       -0.2587      0.032     -8.080      0.000      -0.321      -0.196
resid_area                   0.0023      0.026      0.090      0.928      -0.048       0.053
room_num                     1.0288      0.270      3.806      0.000       0.499       1.559
age                         -0.0047      0.006     -0.733      0.464      -0.017       0.008
teachers                     0.2762      0.062      4.488      0.000       0.156       0.397
poor_prop                   -0.2063      0.033     -6.179      0.000      -0.272      -0.141
n_hos_beds                   0.1168      0.060      1.962      0.050       0.000       0.234
n_hot_rooms                 -0.0641      0.055     -1.157      0.247      -0.173       0.044
rainfall                    -0.0062      0.008     -0.760      0.447      -0.022       0.010
parks                      -20.7777     16.189     -1.283      0.199     -52.508      10.952
airport_YES                 -0.1031      0.208     -0.495      0.621      -0.511       0.305
waterbody_Lake              -0.0258      0.301     -0.086      0.932      -0.616       0.565
waterbody_Lake and River    -0.0092      0.323     -0.028      0.977      -0.642       0.624
waterbody_River              0.2389      0.253      0.944      0.345      -0.257       0.735
avg_dist                    -0.3391      0.092     -3.686      0.000      -0.519      -0.159
============================================================================================
"""

In [78]:
clf_lrs_multi.predict_proba(x_multi)

array([[1.07828719e-01, 8.92171281e-01],
       [3.75846643e-01, 6.24153357e-01],
       [9.99699526e-01, 3.00474106e-04],
       ...,
       [2.61209260e-01, 7.38790740e-01],
       [2.83506123e-01, 7.16493877e-01],
       [1.94396198e-01, 8.05603802e-01]])

In [79]:
y_pred = clf_lrs_multi.predict(x_multi)
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [80]:
y_pred_03 = (clf_lrs_multi.predict_proba(x_multi)[:,1]>=0.3)

In [81]:
y_pred_03

array([ True,  True, False,  True, False, False,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False, False,

In [83]:
from sklearn.metrics import confusion_matrix

In [84]:
confusion_matrix(y_multi,y_pred)

array([[197,  79],
       [ 79, 151]], dtype=int64)

In [85]:
confusion_matrix(y_multi,y_pred_03)

array([[121, 155],
       [ 16, 214]], dtype=int64)

In [86]:
from sklearn.metrics import precision_score,recall_score

In [87]:
precision_score(y_multi,y_pred)

0.6565217391304348

In [88]:
recall_score(y_multi,y_pred)

0.6565217391304348

In [89]:
from sklearn.metrics import roc_auc_score

In [90]:
roc_auc_score(y_multi,y_pred)

0.6851449275362319

In [91]:
#linear_Discriminate_Aanalysis

In [92]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [93]:
clf_lda = LinearDiscriminantAnalysis()

In [94]:
clf_lda.fit(x_multi,y_multi)

LinearDiscriminantAnalysis()

In [95]:
y_pred_lda = clf_lda.predict(x_multi)

In [96]:
y_pred_lda

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [97]:
confusion_matrix(y_multi,y_pred_lda)

array([[192,  84],
       [ 77, 153]], dtype=int64)

In [98]:
#Test_trian_split

In [99]:
from sklearn.model_selection import train_test_split

In [101]:
x_train,x_test,y_train,y_test = train_test_split(x_multi,y_multi,test_size=0.2,random_state=0)

In [102]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(404, 15) (102, 15) (404,) (102,)


In [103]:
clf_LR = LogisticRegression()

In [105]:
clf_LR.fit(x_train,y_train)

C:\Users\OWUSU\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [106]:
y_test_pred = clf_LR.predict(x_test)

In [107]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [108]:
confusion_matrix(y_test,y_test_pred)

array([[36, 22],
       [15, 29]], dtype=int64)

In [109]:
accuracy_score(y_test,y_test_pred)

0.6372549019607843

In [110]:
#KNN

In [111]:
from sklearn import preprocessing

In [112]:
scaler = preprocessing.StandardScaler().fit(x_train)

In [113]:
x_train_s = scaler.transform(x_train)

In [116]:
scaler = preprocessing.StandardScaler().fit(x_test)

In [117]:
x_test_s = scaler.transform(x_test)

In [118]:
from sklearn.neighbors import KNeighborsClassifier

In [119]:
clf_knn_1 = KNeighborsClassifier(n_neighbors = 1)

In [120]:
clf_knn_1.fit(x_train_s,y_train)

KNeighborsClassifier(n_neighbors=1)

In [121]:
confusion_matrix(y_test,clf_knn_1.predict(x_test))

C:\Users\OWUSU\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


array([[45, 13],
       [38,  6]], dtype=int64)

In [122]:
accuracy_score(y_test,clf_knn_1.predict(x_test))

C:\Users\OWUSU\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


0.5

In [123]:
clf_knn_3 = KNeighborsClassifier(n_neighbors = 3)

In [124]:
clf_knn_3.fit(x_train_s,y_train)

KNeighborsClassifier(n_neighbors=3)

In [125]:
confusion_matrix(y_test,clf_knn_3.predict(x_test))

C:\Users\OWUSU\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


array([[54,  4],
       [43,  1]], dtype=int64)

In [126]:
accuracy_score(y_test,clf_knn_3.predict(x_test))

C:\Users\OWUSU\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


0.5392156862745098

In [127]:
# a_model_on_multiple_values_of_k

In [129]:
from sklearn.model_selection import GridSearchCV

In [130]:
params = {'n_neighbors': [1,2,3,4,5,6,7,8,9,10]}

In [131]:
grid_search_cv = GridSearchCV(KNeighborsClassifier(),params)

In [132]:
grid_search_cv.fit(x_train_s,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [133]:
grid_search_cv

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [134]:
grid_search_cv.best_params_

{'n_neighbors': 3}

In [137]:
optimised_KNN = grid_search_cv.best_estimator_

In [138]:
y_test_pred = optimised_KNN.predict(x_test_s)

In [139]:
y_test_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1], dtype=int64)

In [140]:
confusion_matrix(y_test,y_test_pred)

array([[28, 30],
       [23, 21]], dtype=int64)

In [141]:
accuracy_score(y_test,y_test_pred)

0.4803921568627451